Repository PerFumeOnMe/Front-end, pull requests merged in 2025-07, with the labels that each got.

#6 [feat] main page
  public/MainPage/RiaSans-Bold.ttf
  public/MainPage/choose_page_image.png
  public/MainPage/filter.png
  public/MainPage/heart_empty.png
  public/MainPage/heart_filled.png
  public/MainPage/perfume.png
  public/MainPage/search.png
  src/App.tsx
  src/components/MainPage/Banner.tsx
  src/components/MainPage/FilterButton.tsx
  src/components/MainPage/PerfumeCard.tsx
  src/components/MainPage/PerfumeGrid.tsx
  src/components/MainPage/SearchBar.tsx
  src/pages/ChoosePathPage.tsx
  src/pages/FilterPage.tsx
  src/pages/ImageKeywordPage.tsx
  src/pages/MainPage.tsx
  src/types/perfume.ts
Labels: feat

#14 [refactor] main page
  public/MainPage/RiaSans-Bold.ttf
  public/MainPage/heart_empty.png
  public/MainPage/heart_filled.png
  src/assets/MainPage/choose_page_image.png
  src/assets/MainPage/filter.png
  src/assets/MainPage/heart_empty.png
  src/assets/MainPage/heart_filled.png
  src/assets/MainPage/perfume.png
  src/assets/MainPage/search.png
  src/components/MainPage/Banner.tsx
  src/components/MainPage/FilterButton.tsx
  src/components/MainPage/PerfumeCard.tsx
  src/components/MainPage/PerfumeGrid.tsx
  src/components/MainPage/SearchBar.tsx
  src/pages/ChoosePathPage.tsx
  src/pages/MainPage.tsx
  src/styles/colors.css
  src/types/images.d.ts
Labels: bug, refactor

#28 [feat] filter page
  src/App.tsx
  src/assets/MainPage/Logo.png
  src/assets/MainPage/filter.png
  src/assets/MainPage/search.png
  src/components/AllPerfumePage/AllPerfumeHeader.tsx
  src/components/AllPerfumePage/FilterButton.tsx
  src/components/AllPerfumePage/FilterPage/DetailFilter.tsx
  src/components/AllPerfumePage/FilterPage/FilterHeader.tsx
  src/components/AllPerfumePage/FilterPage/FilterSection.tsx
  src/components/AllPerfumePage/SearchBar.tsx
  src/components/AllPerfumePage/SelectedFilters.tsx
  src/components/ImageKeyword/Button.tsx
  src/components/ImageKeyword/ImageKeywordButton.tsx
  src/components/ImageKeyword/ImageKeywordHeader.tsx
  src/components/MainPage/Banner.tsx
  src/components/MainPage/FilterButton.tsx
  src/components/MainPage/Header.tsx
  src/components/MainPage/PerfumeCard.tsx
  src/components/MainPage/PerfumeGrid.tsx
  src/components/MainPage/SearchBar.tsx
  src/components/common/ScentCard.tsx
  src/layout/root-layout.tsx
  src/pages/AllPerfumePage.tsx
  src/pages/FilterPage.tsx
  src/pages/ImageKeyword/ImageKeywordLoading.tsx
  src/pages/ImageKeyword/ImageKeywordPage.tsx
  src/pages/ImageKeywordPage.tsx
  src/pages/MainPage.tsx
  src/types/filter.ts
  src/types/perfume.ts
Labels: feat

#30 [fix] App.tsx 오류
  src/App.tsx
Labels: bug

#38 [Feat] Perfume Detail View
  src/App.tsx
  src/components/PerfumeDetail/CapacityButton.tsx
  src/components/PerfumeDetail/CategoryItem.tsx
  src/components/PerfumeDetail/CategorySection.tsx
  src/components/PerfumeDetail/DescriptionNote.tsx
  src/components/PerfumeDetail/DiffusionInfo.tsx
  src/components/PerfumeDetail/DiffusionTag.tsx
  src/components/PerfumeDetail/ExtraInfo.tsx
  src/components/PerfumeDetail/LastingInfo.tsx
  src/components/PerfumeDetail/NoteCard.tsx
  src/components/PerfumeDetail/PerfumeBasicInfo.tsx
  src/components/PerfumeDetail/PerfumeDescription.tsx
  src/components/PerfumeDetail/PerfumeDetailHeader.tsx
  src/components/PerfumeDetail/PerfumeDetailNavbar.tsx
  src/pages/PerfumeDetailPage.tsx
  src/types/perfume.ts
Labels: feat

#39 ✨ feat: 토스트창 추가 및 SVG → PNG 수정, 공용 컴포넌트 적용(#15)
  package-lock.json
  package.json
  src/assets/Onboarding/amber.png
  src/assets/Onboarding/amber.svg
  src/assets/Onboarding/bergamot.png
  src/assets/Onboarding/bergamot.svg
  src/assets/Onboarding/cedarwood.png
  src/assets/Onboarding/cedarwood.svg
  src/assets/Onboarding/citrus.png
  src/assets/Onboarding/citrus.svg
  src/assets/Onboarding/citrus2.svg
  src/assets/Onboarding/grapefruit.png
  src/assets/Onboarding/grapefruit.svg
  src/assets/Onboarding/iris.png
  src/assets/Onboarding/iris.svg
  src/assets/Onboarding/jasmine.png
  src/assets/Onboarding/musk.png
  src/assets/Onboarding/musk.svg
  src/assets/Onboarding/patchouli.png
  src/assets/Onboarding/patchouli.svg
  src/assets/Onboarding/pink_pepper.png
  src/assets/Onboarding/pink_pepper.svg
  src/assets/Onboarding/return_shape.svg
  src/assets/Onboarding/rose.png
  src/assets/Onboarding/rose.svg
  src/assets/Onboarding/sandalwood.png
  src/assets/Onboarding/sandalwood.svg
  src/assets/Onboarding/vanilla.png
  src/assets/Onboarding/vanilla.svg
  src/assets/Onboarding/vetiver.png
  src/assets/Onboarding/vetiver.svg
  src/assets/Onboarding/white_musk.png
  src/assets/Onboarding/white_musk.svg
  src/components/Onboarding/BottomButton.tsx
  src/components/Onboarding/OnboardingLayout.tsx
  src/components/Onboarding/TopBackButton.tsx
  src/components/common/PageHeader.tsx
  src/components/common/ScentCard.tsx
  src/pages/Onboarding/Step1.tsx
  src/pages/Onboarding/Step2.tsx
  src/pages/Onboarding/Step3.tsx
  src/styles/colors.css
  src/types/scent.ts
  src/types/scentOptions.ts
Labels: feat

#43 ✨ feat:: 다이어리 구현
  git
  package-lock.json
  package.json
  src/App.tsx
  src/components/Diary/Calendar.tsx
  src/components/Diary/CalendarDiary.tsx
  src/layout/root-layout.tsx
  src/pages/Diary/DiaryPage.tsx
  src/pages/Diary/DiaryWritePage.tsx
  src/pages/DiaryPage.tsx
  src/styles/calendar-custom.css
Labels: feat

#50 [Refactor] PerfumeLab Page
  src/App.tsx
  src/assets/PerfumeLab/PerfumeLabBgImage.png
  src/assets/PerfumeLab/cylinder.png
  src/assets/PerfumeLab/cylinder_empty.png
  src/assets/PerfumeLab/masks/base_mask.png
  src/assets/PerfumeLab/masks/middle_mask.png
  src/assets/PerfumeLab/masks/top_mask.png
  src/assets/PerfumeLab/rack.png
  src/components/ImageKeyword/Result/KeywordRecommendation.tsx
  src/components/ImageKeyword/Result/ResultButton.tsx
  src/components/ImageKeyword/Result/SaveCompleteModal.tsx
  src/components/ImageKeyword/Result/SaveNameModal.tsx
  src/components/PerfumeLab/ActionButton.tsx
  src/components/PerfumeLab/BottomSheetModal.tsx
  src/components/PerfumeLab/CylinderItem.tsx
  src/components/PerfumeLab/Header.tsx
  src/components/PerfumeLab/NoteSelectionButton.tsx
  src/components/PerfumeLab/NoteSelectionContent.tsx
  src/components/PerfumeLab/NoteSelectionSection.tsx
  src/components/PerfumeLab/PerfumeBottle.tsx
  src/components/PerfumeLab/PerfumeCylinder.tsx
  src/components/PerfumeLab/PerfumeLabContent.tsx
  src/components/PerfumeLab/PerfumeMakingDisplay.tsx
  src/components/PerfumeLab/PerfumeNoteInfo.tsx
  src/components/PerfumeLab/Result/ButtonSection.tsx
  src/components/PerfumeLab/Result/ContentBox.tsx
  src/components/PerfumeLab/Result/PerfumeCard.tsx
  src/components/PerfumeLab/Result/PerfumeResultDisplay.tsx
  src/components/PerfumeLab/Result/ResultContent.tsx
  src/components/PerfumeLab/Slider.tsx
  src/components/PerfumeLab/VolumeSelectionContent.tsx
  src/components/PerfumeLabPage/PerfumeDisplay.tsx
  src/contexts/PerfumeLabContext.tsx
  src/layout/perfumelab-layout.tsx
  src/pages/perfumeLab/LabLoadingPage.tsx
  src/pages/perfumeLab/LabResultPage.tsx
  src/pages/perfumeLab/PerfumeLabPage.tsx
  src/styles/colors.css
  src/types/PerfumeLab/PerfumeLabResult.ts
Labels: refactor

#54 ✨ feat: 작성 중 x icon 추가 (#1)
  src/components/Signup/SignupIdForm.tsx
  src/components/Signup/SignupInput.tsx
Labels: feat
