Repository PerFumeOnMe/Front-end, pull requests merged in 2025-08, with the labels that each got.

#65 [Network] perfume detail
  src/App.tsx
  src/apis/Fragrance.ts
  src/components/MainPage/PerfumeCard.tsx
  src/components/PerfumeDetail/DescriptionNote.tsx
  src/components/PerfumeDetail/ExtraInfo.tsx
  src/components/PerfumeDetail/PerfumeBasicInfo.tsx
  src/components/PerfumeDetail/PerfumeDescription.tsx
  src/components/PerfumeDetail/PerfumeDetailHeader.tsx
  src/components/PerfumeDetail/PerfumeDetailNavbar.tsx
  src/components/PerfumeDetail/PerfumeExpression.tsx
  src/components/PerfumeLab/ActionButton.tsx
  src/components/PerfumeLab/NoteSelectionContent.tsx
  src/components/PerfumeLab/NoteSelectionSection.tsx
  src/components/PerfumeLab/PerfumeBottle.tsx
  src/components/PerfumeLab/PerfumeCylinder.tsx
  src/components/PerfumeLab/PerfumeLabContent.tsx
  src/components/PerfumeLab/PerfumeNoteInfo.tsx
  src/components/PerfumeLab/Result/ResultContent.tsx
  src/components/PerfumeLab/VolumeSelectionContent.tsx
  src/context/PerfumeDetailContext.tsx
  src/context/PerfumeLabContext.tsx
  src/hooks/usePerfumeDetail.tsx
  src/layout/perfumelab-layout.tsx
  src/pages/PerfumeDetailPage.tsx
  src/types/apis/Fragrance.ts
  src/types/perfume.ts
Labels: network

#79 [network] onboarding page
  src/apis/onboarding.ts
  src/apis/upload.ts
  src/pages/Onboarding/Step1.tsx
  src/pages/Onboarding/Step2.tsx
  src/pages/Onboarding/Step3.tsx
  src/pages/Onboarding/index.tsx
  src/types/scentOptions.ts
Labels: network

#91 refactor:로그인 성공 alert창 삭제
  src/context/AuthContext.tsx
Labels: refactor

#95 fix: name 추가(#93)
  src/context/AuthContext.tsx
Labels: refactor

#108 feat: pbti 로딩 페이지
  src/App.tsx
  src/components/PBTI/Tip/TipContent.tsx
  src/components/PBTI/Tip/TipProgress.tsx
  src/constants/PBTI/ment.ts
  src/pages/PBTI/PBTILoadingPage.tsx
  src/pages/PBTI/PBTIQuestionPage.tsx
Labels: feat

#117 [feat] mypage imagekeyword
  src/App.tsx
  src/apis/ImageKeyword.ts
  src/components/ImageKeyword/Result/KeywordRecommendation.tsx
  src/components/ImageKeyword/Result/KeywordResultHeader.tsx
  src/components/MyPage/FavoritesAndRecommendations.tsx
  src/components/MyPage/MyPageKeywordRecommendationCard.tsx
  src/pages/ChoosePathPage.tsx
  src/pages/ImageKeyword/ImageKeywordLoading.tsx
  src/pages/ImageKeyword/ImageKeywordResult.tsx
  src/types/ImageKeyword/imageKeyword.ts
  src/types/apis/ImageKeyword.ts
Labels: feat

#126 [fix] qa2
  src/components/AllPerfumePage/SearchBar.tsx
  src/components/ImageKeyword/Result/KeywordResultHeader.tsx
  src/components/ImageKeyword/Result/SaveCompleteModal.tsx
  src/components/ImageKeyword/Result/SaveNameModal.tsx
  src/pages/AllPerfumePage.tsx
  src/pages/ImageKeyword/ImageKeywordLoading.tsx
Labels: fix
